{
 "title": "Spring Batch Prometheus",
 "description": "Dashboard for Spring Batch applications instrumented with Micrometer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "job_name",
    "query": "label_values(spring_batch_job_seconds_max, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "Spring Batch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spring_batch_job_seconds_max{job_name=\"$job_name\"}",
     "legendFormat": "{{ job_name }}"
    }
   ]
  },
  {
   "title": "Step Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spring_batch_step_seconds_max{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_step_name}}"
    }
   ]
  },
  {
   "title": "Item Read Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_batch_item_read_seconds_max{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_item_read_step_name}} "
    }
   ]
  },
  {
   "title": "Item Process Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_batch_item_process_seconds_max{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_item_process_step_name}} "
    }
   ]
  },
  {
   "title": "Item Write Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_batch_chunk_write_seconds_max{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_chunk_write_step_name}} "
    }
   ]
  },
  {
   "title": "Item Read Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "spring_batch_item_read_seconds_count{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_item_read_step_name}}"
    }
   ]
  },
  {
   "title": "Item Process Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "spring_batch_item_process_seconds_count{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_item_process_step_name}}"
    }
   ]
  },
  {
   "title": "Item Write Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "spring_batch_chunk_write_seconds_count{job_name=\"$job_name\"}",
     "legendFormat": "{{spring_batch_chunk_write_step_name}}"
    }
   ]
  }
 ]
}