### 주문
POST http://localhost:8080/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1727111685047_9c11c683-4726-4908-aa9c-f30ac3f583ab",
      "quantity": 2
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 완료
POST http://localhost:8080/v1/orders/6/payment
Content-Type: application/json

{
  "success": true
}

### 결제 실패
POST http://localhost:8080/v1/orders/3/payment
Content-Type: application/json

{
  "success": false
}

### 주문 완료
POST http://localhost:8080/v1/orders/6/complete
Content-Type: application/json


### 주문 취소
POST http://localhost:8080/v1/orders/2/cancel
Content-Type: application/json
